### ISSUE TITLE
Progress of sender not accessible

### ISSUE THREAD

**Issue by ulbrich** [jane/JaneSliderControl#11]
Hi,

thanks for this great slider component — we love it! :-) Here's a small issue we found, though (release version 2.0.1). When reading the progress value in our actions, we get

`'progress' is inaccessible due to 'internal' protection level`

and that's true, as `progress` is set to

`fileprivate(set) var progress:Float = 0.0`

hiding its value from the outside.

Best,
Jan

**Comment by gordontucker** [comment]
Release `2.0.3` Has this property as public getter.

**Comment by ulbrich** [comment]
Wow, thanks for the fast fix: Great!

**Comment by minghoe** [comment]
how to call the progress function?
