### ISSUE TITLE
Which method or attribute do i call to programmatically set the toggle state?

### ISSUE THREAD

**Issue by v15a1** [jane/JaneSliderControl#17]
I would like to know if there's a method, or an attribute that i can invoke or set to set the slide state (ex ;- on/off) of the slider

**Comment by gordontucker** [comment]
You should be able to set the `progress` property to 0 and 1 to turn it off/on respectively.

**Comment by v15a1** [comment]
<img width="461" alt="Screenshot 2020-08-20 at 23 59 06" src="https://user-images.githubusercontent.com/46480892/90810783-24eb4800-e341-11ea-8b6e-5891bef03656.png">

i tried, but it ends up like this. any suggestions?

**Comment by gordontucker** [comment]
Hmm. That doesn't look right. I'll update this to allow setting the progress like you should be able to.

**Comment by v15a1** [comment]
just for reference and to ensure it's not on my side. This is how it's supposed to go yea. See below
`            statusSlider.sliderControl.progress = 1
`

**Comment by gordontucker** [comment]
You are correct. I've added the function `setProgress(CGFloat, animated: Bool)` for you to set the state manually in version 2.1.1.

**Comment by v15a1** [comment]
thank you
