### ISSUE TITLE
Need some space for all sides of slider:UIView.

### ISSUE THREAD

**Issue by MiteshiOS** [jane/JaneSliderControl#19]
I want to add some space on each side of slider:UIView. Can you please help me how can I achieve this.
Please check reference screenshot for how i want.
![Screenshot 2021-06-01 at 5 55 53 PM](https://user-images.githubusercontent.com/17427703/120323043-b214f180-c302-11eb-897e-ae40e8735f6d.png)

Thank you

**Comment by MiteshiOS** [comment]
@gordontucker Can you please provide any suggestions on this one.

**Comment by gordontucker** [comment]
This isn't inherently supported. You can achieve this on your own by wrapping the slider in another uiview that has the same color as the background and a rounded corder of the new size of the slider. Good luck
